[package]
name = "confidante"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bytes = "1.1.0"
futures = "0.3.19"
rand = "0.8.5"
rand_chacha = "0.3.1"
rustyxml = { package = "RustyXML", version = "0.3.0" }
sasl = "0.5.0"
tokio = { version = "1", features = ["full"] }
tokio-util =  { version = "0.7.0", features = ["codec"] }
