[package]
name = "confidante"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { version = "0.5.3", features = ["std"] }
anyhow = "1.0.60"
base64 = "0.22.1"
bytes = "1.1.0"
config = { version = "0.14.0", features = ["yaml"] }
digest = "0.10.3"
futures = "0.3.19"
pin-project = "1.1.4"
quick-xml = "0.36.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.10.2"
rustls = "0.23.1"
rustyxml = { package = "RustyXML", version = "0.3.0" }
sha1 = "0.10.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_with = "3.6.0"
thiserror = "1.0.32"
tokio = { version = "1.18.1", features = ["full"] }
tokio-rustls = "0.26.0"
tokio-stream = "0.1.14"
uuid = { version = "1.2.2", features = ["v4"] }
rustls-native-certs = "0.7.0"
rustls-pemfile = "2.1.1"
password-hash = "0.5.0"
sha2 = "0.10.8"
scram-rs = { version = "0.12.0", features = ["use_ring"] }
