[package]
name = "confidante"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
futures = "0.3.19"
tokio = { version = "1", features = ["full"] }
tokio-util =  { version = "0.7.0", features = ["codec"] }
rustyxml = { package = "RustyXML", version = "0.3.0" }
